// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udndzvxwnirpxsemmxbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkbmR6dnh3bmlycHhzZW1teGJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDYzOTYsImV4cCI6MjA2MzY4MjM5Nn0.mT48nXW_m9LCzBFwK-p6aZRitlKbg81Y3MYKw0LJx4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);